browser=chrome
URL_1=https://www.facebook.com/
URL_2=https://www.google.com/
driverProperty=webdriver.chrome.driver
driverPath=.\\src\\com\\projectName\\drivers\\
!--log4JPropertiesFileLoc=.\\src\\com\\project\\repository\\log4j.properties
log4JPropertiesFileLoc=C:\\Users\\Tejaswini\\eclipse-workspace\\onlinejavatraining\\log4j.properties
ExcelSheetName=Sheet1
